---
# CHECK LOCAL PUB KEY

- name: Turn on debug mode
  ansible.builtin.debug:
    var: action

- name: Check all variables have value
  ansible.builtin.fail:
    msg: File path_to_local_key.pub does not exist
  when: vars[item] == "" or vars[item] == None
  loop:
    - user_name
    - user_group
    - task
    - path_to_local_key

- name: Install tasks
  when: task == "install"
  block:
    - name: "Create group: {{ user_group }}"
      ansible.builtin.group:
        name: "{{ user_group }}"
        state: present

    - name: "Create user: {{ user_name }}"
      ansible.builtin.user:
        name: "{{ user_name }}"
        append: true
        state: present
        groups: "{{ user_group }}"
        createhome: true
        shell: /bin/bash

    - name: "Allow to have passwordless sudo for user: {{ user_name }}"
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        line: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s

    - name: "Set up authorized key for user: {{ user_name }}"
      ansible.posix.authorized_key:
        user: "{{ user_name }}"
        key: "{{ lookup('file', '{{path_to_local_key}}') }}"

    - name: "Create symbolic link to root .vimrc file"
      ansible.builtin.file:
        src: /root/.vimrc
        dest: "/home/{{ user_name }}/.vimrc"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0644"
        state: link

- name: Uninstall tasks
  when: task == 'uninstall'
  block:
    - name: "Remove authorized key for user: {{ user_name }}"
      ansible.posix.authorized_key:
        user: "{{ user_name }}"
        state: absent
        key: "{{ lookup('file', '{{path_to_local_key}}') }}"

    - name: "Remove user: {{ user_name }}"
      ansible.builtin.user:
        name: "{{ user_name }}"
        remove: true
        state: absent

    - name: "Remove group: {{ user_group }}"
      ansible.builtin.group:
        name: "{{ user_group }}"
        state: absent

    - name: "Delete permissions for user: {{ user_name }}"
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: absent
        line: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s
